# -*- coding: utf-8 -*-
"""GROUP_04.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/194HqiNTvN71RqZeInZdvivlF4dH-pnwG
"""

# bd_calculator.py
# מחשבון המרות: עשרוני <-> בינארי (כולל טיפול במספרים שליליים)

def is_valid_binary(s: str) -> bool:
    """בודק אם מחרוזת היא בינארית חוקית (כולל סימן שלילי)."""
    if not s:
        return False
    # אפשרות למינוס בהתחלה
    if s[0] == "-":
        s = s[1:]
    return all(ch in ("0", "1") for ch in s) and len(s) > 0


def is_valid_decimal(s: str) -> bool:
    """בודק אם מחרוזת היא עשרונית חוקית (כולל שלילית)."""
    if not s:
        return False
    if s[0] == "-":
        s = s[1:]
    return s.isdigit() and len(s) > 0


def binary_to_decimal(bin_str: str) -> int:
    """המרה מבינארי לעשרוני (כולל שלילי)."""
    if not is_valid_binary(bin_str):
        raise ValueError("קלט בינארי לא תקין: מותר רק 0/1 עם אפשרות ל-'-' בתחילה")

    sign = -1 if bin_str.startswith("-") else 1
    bin_str = bin_str.lstrip("-").lstrip("0") or "0"

    value = int(bin_str, 2)
    return sign * value


def decimal_to_binary(dec_str: str) -> str:
    """המרה מעשרוני לבינארי (כולל שלילי)."""
    if not is_valid_decimal(dec_str):
        raise ValueError("קלט עשרוני לא תקין: מותר רק ספרות עם אפשרות ל-'-' בתחילה")

    n = int(dec_str)
    if n == 0:
        return "0"

    # שימוש ב-bin למספר שלילי גם עובד, אבל נוריד את הקידומת "0b"
    if n < 0:
        return "-" + bin(abs(n))[2:]
    return bin(n)[2:]


def show_menu():
    print("================================")
    print("  ממיר בסיסים - עשרוני / בינארי")
    print("================================")
    print("1. המרה מבינארי לעשרוני")
    print("2. המרה מעשרוני לבינארי")
    print("3. יציאה")
    print("--------------------------------")


def main():
    while True:
        show_menu()
        choice = input("בחרי אפשרות (1/2/3): ").strip()
        if choice == "1":
            s = input("הכניסי מספר בינארי (אפשר גם עם סימן שלילי): ").strip()
            try:
                val = binary_to_decimal(s)
                print(f"תוצאה בעשרוני: {val}")
            except ValueError as e:
                print(f"שגיאה: {e}")
        elif choice == "2":
            s = input("הכניסי מספר עשרוני (אפשר גם עם סימן שלילי): ").strip()
            try:
                bits = decimal_to_binary(s)
                print(f"תוצאה בבינארי: {bits}")
            except ValueError as e:
                print(f"שגיאה: {e}")
        elif choice == "3":
            print("להתראות!")
            break
        else:
            print("בחירה לא תקפה, נסי שוב.")


if __name__ == "__main__":
    main()